// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htyfoodvumnqwdysybzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eWZvb2R2dW1ucXdkeXN5Ynp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDc0NDIsImV4cCI6MjA2OTgyMzQ0Mn0.aXfvfKge7aggpv_w2-Cv30MO0S8c5J2v9AKs9tab0QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});